name: ci

on:
  schedule:
    - cron: 0 0 * * 1 
  push:
    branches: main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Login to GitHub Container Registry
#        uses: docker/login-action@v1 
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push amd64
        id: docker_build_amd64
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64 
          push: true
          tags: |
            chillfre4k/latex:latest
          #  ghcr.io/b-reich/latex:latest
          #cache-from: type=registry,ref=chillfre4k/latex:latest
          #cache-to: type=inline
      -
        name: Build and push arm64
        id: docker_build_arm64
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64 
          push: true
          tags: |
            chillfre4k/latex:latest
          #  ghcr.io/b-reich/latex:latest
          #cache-from: type=registry,ref=chillfre4k/latex:latest
          #cache-to: type=inline
      -
        name: Build and push armv7
        id: docker_build_armv7
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v7 
          push: true
          tags: |
            chillfre4k/latex:latest
          #  ghcr.io/b-reich/latex:latest
          #cache-from: type=registry,ref=chillfre4k/latex:latest
          #cache-to: type=inline
      - 
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  
  push-docker-readme:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: chillfre4k/latex
